services:
  - type: web
    name: queueblaze
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn queueblaze.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: queueblaze-db
          property: connectionString
    postgres:
      name: queueblaze-db
      plan: free
